### ISSUE TITLE
I think it stopped working in the album section, as it searchs for nothing.

### ISSUE THREAD

**Issue by romanoh** [Purfview/Discogs-Scout#1]
I think it stopped working, as it returns on the search nothing.
Inside the album.
firefox
https://i.imgur.com/veJ7DIV.png

i don't know its because of the beta site.( i am not using it)

**Comment by Purfview** [comment]
It looks that they changed there something yesterday, hopefully today I'll fix it, and will add support for beta and all other pages.
Thanks for the report.

**Comment by Purfview** [comment]
Should be fixed in v2.0.
