### ISSUE TITLE
Spotify search error

### ISSUE THREAD

**Issue by romanoh** [Purfview/Discogs-Scout#15]
If i search per example: Duncan Dhu – Entre Salitre Y Sudor,
it results in:
https://i.imgur.com/thdaPDC.png
no results 

but if i search:
https://i.imgur.com/BY9SiWN.png

it shows

thank you for your script, it is wonderful.

**Comment by Purfview** [comment]
Looks OK.
There is no "Entre Salitre Y Sudor" release on Spotify, only a song by this name. 
There is no feature in the script to search for the songs.
