### ISSUE TITLE
when Vol. Volume in Album Name

### ISSUE THREAD

**Issue by magnaux** [Purfview/Discogs-Scout#16]
exmple  VA - Album name Vol.1 ..... if added as  VA - Album Name Vol. 1 it is not found  (Discogs <-> red)
(when Vol. search both with space and without )
(maybe add option to have Release Label in search filter too [RED])

**Comment by magnaux** [comment]
[Gregory Shiff](https://www.discogs.com/artist/44914-Gregory-Shiff) - [Exit And Entrance #1 EP](https://www.discogs.com/release/54803-Gregory-Shiff-Exit-And-Entrance-1-EP)     <-> Gregory Shiff - Exit and Entrance 1

**Comment by Purfview** [comment]
Dupe https://github.com/Purfview/Discogs-Scout/issues/3
