### ISSUE TITLE
Doesn't support non English languages

### ISSUE THREAD

**Issue by Catarax** [Purfview/Discogs-Scout#18]
I have a /fr/ for all my discogs links.
Like 
https://www.discogs.com/fr/master/600753-Drake-Nothing-Was-The-Same

So I modified the script like that 

// @include      https://www.discogs.com/fr/artist/*
// @include      https://www.discogs.com/fr/master/*
// @include      https://www.discogs.com/fr/release/*
// @include      https://www.discogs.com/fr/label/*
// @include      https://www.discogs.com/fr/user/*/collection*
// @include      https://www.discogs.com/fr/wantlist*
// @include      https://www.discogs.com/fr/mywantlist*
// @include      https://www.discogs.com/fr/lists/*

However I don't understand how to setup again the script.

Also Tidal store links are broken, it's possible to have something like
https://listen.tidal.com/search?q={search} 
instead of the store?

Thanks!

**Comment by Purfview** [comment]
All that should be fixed in v2.6.
The script's settings you can find at your monkey's icon.
