### ISSUE TITLE
Wantlist Disabled Large Cover useless notification

### ISSUE THREAD

**Issue by Catarax** [Purfview/Discogs-Scout#19]
Despite Wantlist disabled, I still get that notification on Big cover mode :

https://img001.prntscr.com/file/img001/QJQ8zIreRVqioVT70Dm6rQ.png

URL
https://www.discogs.com/fr/mywantlist?layout=big
(can also become https://www.discogs.com/fr/mywantlist when big cover used by default)

https://img001.prntscr.com/file/img001/a014bej3QYKwWDaRy4B8mw.png

Thanks!

**Comment by Purfview** [comment]
Should be fixed in v2.7.
