### ISSUE TITLE
Own WantList doesn't work

### ISSUE THREAD

**Issue by magnaux** [Purfview/Discogs-Scout#2]
looks like wantlist doesnt work yet 
i am getting " error.. plz report url"

Collection works !

**Comment by Purfview** [comment]
Ah, it's your own wantlist, yep it doesn't work for some reason, it will be fixed asap.

**Comment by Purfview** [comment]
Check if it works with v.2.1.

**Comment by magnaux** [comment]
thanks so much !!! it works.. now i can dig my 4000++ items wantlist much faster !!!
