### ISSUE TITLE
Various on RED

### ISSUE THREAD

**Issue by magnaux** [Purfview/Discogs-Scout#3]
heey 
i was thinking if maybe using Record label when searching various could solve showing most various as existing 
from wantlist on RED
![Screenshot 2022-07-14 at 06-54-42 My Wantlist - Discogs](https://user-images.githubusercontent.com/107857394/178895535-a8ee9af0-38be-49d9-a284-5cfb145628f7.png)

thanks alot

**Comment by Purfview** [comment]
"Showing" where?

**Comment by magnaux** [comment]
from wantlist on RED

**Comment by Purfview** [comment]
It shows as existing in your screenshot [green border = existing].

**Comment by magnaux** [comment]
hello , although it shows as existing .. the results shown on red page are
random,

is it possible to add edition label for better approach ?
when i have time i will try collect all the releases that although script
says they dont exist , they exist ..

**Comment by Purfview** [comment]
> hello , although it shows as existing .. the results shown on red page are random, is it possible to add edition label for better approach ?

Dunno as I can't check RED. Post a screenshot of search fields and results.
