### ISSUE TITLE
[Tracker Request] Animebytes and Bemaniso

### ISSUE THREAD

**Issue by PockyPoku** [Purfview/Discogs-Scout#4]
Looking to see if support for https://animebytes.tv and https://bemaniso.ws would be possible. I can send an invite for the latter if needed! 

Thank you! Love the userscript btw!

**Comment by Purfview** [comment]
For animebytes I could reuse entry from IMDb Scout, you would need to post URL when you search there for Band Album, select music categories before doing search.

You can send bemaniso invite to purfview at protonmail com

**Comment by PockyPoku** [comment]
URL: https://animebytes.tv/torrents2.php?tags=-lolicon+-shotacon+&sort=relevance&way=desc&showhidden=0&cdtype[album]=1&cdtype[soundtrack]=1&cdtype[single]=1&cdtype[ep]=1&cdtype[compilation]=1&cdtype[remix_cd]=1&cdtype[live_album]=1&cdtype[spokenword]=1&cdtype[image_cd]=1&cdtype[vocal_cd]=1&theme[Opening]=1

Hope that works alright. Thank you! Invite sent.

**Comment by Purfview** [comment]
I don't see you searching anything in that URL, you need to search for something.

Anyway, I tried to guess correct URL, check if it works properly:

Added AnimeBytes - https://github.com/Purfview/Discogs-Scout/commit/2a02624ec8273e97b75fa1baa611844c9f4d1011
Added Bemaniso- https://github.com/Purfview/Discogs-Scout/commit/573a34d047b45214f1f0eb845d86430069b3feef

**Comment by PockyPoku** [comment]
Works! Thank you Purfview. Have a good one! :)

**Comment by PockyPoku** [comment]
A complete URL for future reference (should have included this originally, apologies.).

https://animebytes.tv/torrents2.php?artistnames=Suga+Shikao&groupname=Sweet&tags=-lolicon+-shotacon+&sort=relevance&way=desc&showhidden=0&cdtype%5Balbum%5D=1&cdtype%5Bsoundtrack%5D=1&cdtype%5Bsingle%5D=1&cdtype%5Bep%5D=1&cdtype%5Bcompilation%5D=1&cdtype%5Bremix_cd%5D=1&cdtype%5Blive_album%5D=1&cdtype%5Bspokenword%5D=1&cdtype%5Bimage_cd%5D=1&cdtype%5Bvocal_cd%5D=1

**Comment by Purfview** [comment]
That URL is advanced search, I guess. 

What I used in script is basic search, if it works then I'll leave it as it is.
By "works" I mean that icon should show green border on found and yellow border on not found.
